<a href="https://colab.research.google.com/github/DIabelski2/Data-Science/blob/main/wprwadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
print('Hello world')

Hello world


In [6]:
import numpy as np
np. __version__

'2.0.2'

In [7]:
#print(dir(np))

In [8]:
#help(np.array)

1D Array


In [9]:
x = np.array([1, 4,3])
x

array([1, 4, 3])

In [10]:
print(x)

[1 4 3]


In [11]:
type(x)

numpy.ndarray

In [12]:
x.ndim

1

In [13]:
x.shape

(3,)

In [14]:
x.dtype

dtype('int64')

float

In [15]:
x= np.array([1.3, 2.4, 1.43])
print(x)

[1.3  2.4  1.43]


In [16]:
x.dtype

dtype('float64')

2D array

In [17]:
x = np.array([[2,1],[5,1]])
x

array([[2, 1],
       [5, 1]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [20]:
x.dtype

dtype('int64')

In [21]:
y= np.array([[2,1,5], [3,5,7]])
y

array([[2, 1, 5],
       [3, 5, 7]])

In [22]:
y.shape

(2, 3)

3D array

In [23]:
 m = np.array([
    [[3,5,6],
     [4,6,4]],
    [[4,5,7],
     [5,7,9]],
    [[3,5,6],
     [4,67,8]]
 ])
 m

array([[[ 3,  5,  6],
        [ 4,  6,  4]],

       [[ 4,  5,  7],
        [ 5,  7,  9]],

       [[ 3,  5,  6],
        [ 4, 67,  8]]])

In [24]:
m.ndim


3

In [25]:
m.shape

(3, 2, 3)


**TYPY DANYCH**

In [26]:
a = np.array([4,3,2])
a.dtype

dtype('int64')

In [27]:
a = np.array([2.3,5.5,7])
a.dtype

dtype('float64')

In [28]:
a = np.array([4,6,4], dtype='float')
a.dtype

dtype('float64')

In [29]:
print(a)

[4. 6. 4.]


liczby zlozone (complex)

In [30]:
b = np.array([5,6,7], dtype=(complex))
b.dtype

dtype('complex128')

In [31]:
print(b)

[5.+0.j 6.+0.j 7.+0.j]


In [33]:
a = np.array([True, False])
a.dtype

dtype('bool')

**Tworzenie tablic**

In [36]:
np.zeros(shape=(4,10), dtype=(int))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
np.full(shape = (3,3) , fill_value=5.6, dtype='float')

array([[5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6]])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [42]:
np.arange(start = 10, stop = 20, step = 2)

array([10, 12, 14, 16, 18])

In [44]:
np.arange(start = 20, stop = 8, step = -2)

array([20, 18, 16, 14, 12, 10])

In [45]:
np.arange(start = 20, stop = 15, step = -0.5)

array([20. , 19.5, 19. , 18.5, 18. , 17.5, 17. , 16.5, 16. , 15.5])

In [48]:
np.linspace(start = 0 , stop = 10, num=9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [49]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])