<a href="https://colab.research.google.com/github/DIabelski2/Data-Science/blob/main/wprwadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
print('Hello world')

Hello world


In [69]:
import numpy as np
np. __version__

'2.0.2'

In [ ]:
#print(dir(np))

In [ ]:
#help(np.array)

1D Array


In [72]:
x = np.array([1, 4,3])
x

array([1, 4, 3])

In [73]:
print(x)

[1 4 3]


In [74]:
type(x)

numpy.ndarray

In [75]:
x.ndim

1

In [76]:
x.shape

(3,)

In [77]:
x.dtype

dtype('int64')

float

In [78]:
x= np.array([1.3, 2.4, 1.43])
print(x)

[1.3  2.4  1.43]


In [79]:
x.dtype

dtype('float64')

2D array

In [80]:
x = np.array([[2,1],[5,1]])
x

array([[2, 1],
       [5, 1]])

In [81]:
x.ndim

2

In [82]:
x.shape

(2, 2)

In [83]:
x.dtype

dtype('int64')

In [84]:
y= np.array([[2,1,5], [3,5,7]])
y

array([[2, 1, 5],
       [3, 5, 7]])

In [85]:
y.shape

(2, 3)

3D array

In [93]:
 m = np.array([
    [[3,5,6],
     [4,6,4]],
    [[4,5,7],
     [5,7,9]],
    [[3,5,6],
     [4,67,8]]
 ])
 m

array([[[ 3,  5,  6],
        [ 4,  6,  4]],

       [[ 4,  5,  7],
        [ 5,  7,  9]],

       [[ 3,  5,  6],
        [ 4, 67,  8]]])

In [94]:
m.ndim


3

In [95]:
m.shape

(3, 2, 3)


**TYPY DANYCH**

In [96]:
a = np.array([4,3,2])
a.dtype

dtype('int64')

In [98]:
a = np.array([2.3,5.5,7])
a.dtype

dtype('float64')

In [104]:
a = np.array([4,6,4], dtype='float')
a.dtype

dtype('float64')

In [102]:
print(a)

[4. 6. 4.]


liczby zlozone (complex)

In [105]:
b = np.array([5,6,7], dtype=(complex))
b.dtype

dtype('complex128')

In [106]:
print(b)

[5.+0.j 6.+0.j 7.+0.j]
