<a href="https://colab.research.google.com/github/DIabelski2/Data-Science/blob/main/wprwadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello world')

Hello world


In [ ]:
import numpy as np
np. __version__

'2.0.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array


In [ ]:
x = np.array([1, 4,3])
x

array([1, 4, 3])

In [ ]:
print(x)

[1 4 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(3,)

In [ ]:
x.dtype

dtype('int64')

float

In [ ]:
x= np.array([1.3, 2.4, 1.43])
print(x)

[1.3  2.4  1.43]


In [ ]:
x.dtype

dtype('float64')

2D array

In [ ]:
x = np.array([[2,1],[5,1]])
x

array([[2, 1],
       [5, 1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y= np.array([[2,1,5], [3,5,7]])
y

array([[2, 1, 5],
       [3, 5, 7]])

In [ ]:
y.shape

(2, 3)

3D array

In [ ]:
m = np.array([
    [1.4,13,2,36],
    [3,5.2,4.2],
    [7,3.4,5]

])

print(m)