<a href="https://colab.research.google.com/github/DIabelski2/Data-Science/blob/main/wprwadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print('Hello world')

Hello world


In [5]:
import numpy as np
np. __version__

'2.0.2'

In [6]:
#print(dir(np))

In [7]:
#help(np.array)

1D Array


In [8]:
x = np.array([1, 4,3])
x

array([1, 4, 3])

In [9]:
print(x)

[1 4 3]


In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [12]:
x.shape

(3,)

In [13]:
x.dtype

dtype('int64')

float

In [14]:
x= np.array([1.3, 2.4, 1.43])
print(x)

[1.3  2.4  1.43]


In [15]:
x.dtype

dtype('float64')

2D array

In [16]:
x = np.array([[2,1],[5,1]])
x

array([[2, 1],
       [5, 1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [19]:
x.dtype

dtype('int64')

In [20]:
y= np.array([[2,1,5], [3,5,7]])
y

array([[2, 1, 5],
       [3, 5, 7]])

In [21]:
y.shape

(2, 3)

3D array

In [22]:
 m = np.array([
    [[3,5,6],
     [4,6,4]],
    [[4,5,7],
     [5,7,9]],
    [[3,5,6],
     [4,67,8]]
 ])
 m

array([[[ 3,  5,  6],
        [ 4,  6,  4]],

       [[ 4,  5,  7],
        [ 5,  7,  9]],

       [[ 3,  5,  6],
        [ 4, 67,  8]]])

In [23]:
m.ndim


3

In [24]:
m.shape

(3, 2, 3)


**TYPY DANYCH**

In [25]:
a = np.array([4,3,2])
a.dtype

dtype('int64')

In [26]:
a = np.array([2.3,5.5,7])
a.dtype

dtype('float64')

In [27]:
a = np.array([4,6,4], dtype='float')
a.dtype

dtype('float64')

In [28]:
print(a)

[4. 6. 4.]


liczby zlozone (complex)

In [29]:
b = np.array([5,6,7], dtype=(complex))
b.dtype

dtype('complex128')

In [30]:
print(b)

[5.+0.j 6.+0.j 7.+0.j]


In [31]:
a = np.array([True, False])
a.dtype

dtype('bool')

**Tworzenie tablic**

In [32]:
np.zeros(shape=(4,10), dtype=(int))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.full(shape = (3,3) , fill_value=5.6, dtype='float')

array([[5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [36]:
np.arange(start = 10, stop = 20, step = 2)

array([10, 12, 14, 16, 18])

In [37]:
np.arange(start = 20, stop = 8, step = -2)

array([20, 18, 16, 14, 12, 10])

In [38]:
np.arange(start = 20, stop = 15, step = -0.5)

array([20. , 19.5, 19. , 18.5, 18. , 17.5, 17. , 16.5, 16. , 15.5])

In [39]:
np.linspace(start = 0 , stop = 10, num=9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [40]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
A.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Działanie na tablicach**

In [44]:
A = np.array([5,1,3,5])
B = np.array([3,1,5,7])
print(A)
print(B)

[5 1 3 5]
[3 1 5 7]


In [45]:
A+B

array([ 8,  2,  8, 12])

In [46]:
A*B

array([15,  1, 15, 35])

In [47]:
A-B

array([ 2,  0, -2, -2])

In [48]:
np.add(A,B)

array([ 8,  2,  8, 12])

In [49]:
np.subtract(A,B)

array([ 2,  0, -2, -2])

In [50]:
np.multiply(A,B)

array([15,  1, 15, 35])

In [51]:
A + 4


array([9, 5, 7, 9])

In [52]:
A / 2

array([2.5, 0.5, 1.5, 2.5])

In [53]:
A + 3*B

array([14,  4, 18, 26])

In [54]:
print(A)

[5 1 3 5]


In [55]:
X = np.array([[1,4] , [6,4]])
Y = np.array([[3,2] , [8,5]])
print(X)
print(Y)

[[1 4]
 [6 4]]
[[3 2]
 [8 5]]


In [56]:
X*Y

array([[ 3,  8],
       [48, 20]])

Zwykle mnożeenie macierzowe

In [57]:
np.dot(X,Y)

array([[35, 22],
       [50, 32]])

In [58]:
X.dot(Y)

array([[35, 22],
       [50, 32]])

In [59]:
Y.dot(X)

array([[15, 20],
       [38, 52]])

In [60]:
X @ Y

array([[35, 22],
       [50, 32]])

**LOSOWE**

In [61]:
np.random.seed(0)

In [62]:
np.random.rand(1,10)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]])

In [63]:
np.random.randn(3,4,4)

array([[[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
        [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
        [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
        [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567]],

       [[ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
        [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
        [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
        [-0.38732682, -0.30230275, -1.04855297, -1.42001794]],

       [[-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
        [-1.25279536,  0.77749036, -1.61389785, -0.21274028],
        [-0.89546656,  0.3869025 , -0.51080514, -1.18063218],
        [-0.02818223,  0.42833187,  0.06651722,  0.3024719 ]]])

In [64]:
np.random.randint(1,10,6)

array([1, 3, 8, 3, 3, 4])

In [65]:
np.random.randint(low = 19, high=23, size = 3)

array([21, 22, 22])

In [66]:
np.random.choice(['python', 'java', 'sql'])

np.str_('sql')

In [67]:
a =np.random.choice([1,3,4,7])
print(a)

4


In [68]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

funkcje

**WYCIAGANIE WARTOSCI MAX**

In [69]:
A = np.random.rand(5)
print(A)

[0.56660145 0.26538949 0.52324805 0.09394051 0.5759465 ]


In [72]:
np.argmax(A)


np.int64(4)

In [75]:
A[np.argmax(A)]

np.float64(0.5759464955561793)

In [79]:
np.argsort(A)

array([3, 1, 2, 0, 4])